sudo: required
language: node_js
node_js:
    - node
services:
    - docker
env:
    global:
        - DISABLE_SANDBOX=true
jobs:
    include:
        - stage: "Tests"
          name: "Unit"
          script: npm run test
